background {
    monitor =
    path = ~/Downloads/wallpaper.jpg
    blur_passes = 0
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(255, 255, 255)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(255, 255, 255)
    placeholder_text = <i>Password...</i>
    position = 0, 0
    halign = center
    valign = center
}
