# Git branch
[git_branch]
symbol = " "
style = "bold #f5c2e7"

# Git status (added, modified, removed)
[git_status]
style = "bold #f38ba8"

# Git state (merging, rebasing)
[git_state]
style = "bold #fab387"

# Character (prompt symbol) – new version uses 'success' module
[status] 
format = "[$symbol]($style) " # optional, can remove if unnecessary
